import Head from "next/head"
import Image from "next/image"
import logo from "public/devtter-logo.png"
import styled from "styled-components"
import { colors } from "src/styles/theme"
import { Button } from "src/components/Button"
import GitHub from "src/components/Icons/GitHub"
import { loginWithGitHub } from "../firebase/client"
import { useEffect } from "react"
import { useRouter } from "next/router"
import { useDispatch, useSelector } from "react-redux"
import { getUser } from "src/redux/selectors/user"
const Title = styled.h1`
  color: ${colors.primary};
  font-weight: 800;
  text-align: center;
`

const Subtitle = styled.h2`
  color: ${colors.secondary};
  text-align: center;
`

const Container = styled.section`
  height: 100%;
  display: grid;
  place-content: center;
  place-items: center;
  padding: 40px;
`

export default function Index() {
  const user = useSelector(state => getUser(state))
  const dispatch = useDispatch();
  const router = useRouter()

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  const handleClick = () => {
    loginWithGitHub(dispatch)
  }
  return (
    <>
      <Head>
        <title>Devtter 🐤</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Image src={logo} alt="logo" width={120} height={120} />
        <Title>Devtter</Title>
        <Subtitle>Talk about development with developers 👩‍💻👨‍💻</Subtitle>
        <div style={{ marginTop: 80 }}>
          <Button buttonType="secondary" onClick={handleClick}>
            <GitHub width={24} height={24} fill="#fff" />
            Login with Github
          </Button>
        </div>
      </Container>
    </>
  )
}
