import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import AppLayout from '../components/AppLayout';
import logo from '../public/devtter-logo.png';
import styled  from 'styled-components';
import { colors } from '../styles/theme';
import { Button } from '../components/Button';
import GitHub from '../components/Icons/GitHub';
import { loginWithGitHub, onAuthState } from '../firebase/client';
import { useState, useEffect } from 'react';

const Title = styled.h1`
  color: ${colors.primary};
  font-weight: 800;
  text-align: center;
`;

const Subtitle = styled.h2`
  color: ${colors.secondary};
  text-align: center;
`;

const Container = styled.section`
  height: 100%;  
  display: grid;
  place-content: center;
  place-items: center;
  padding: 40px;
`; 

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    onAuthState(setUser)
  }, []);

  const handleClick = () => { 
    loginWithGitHub()
      .then(setUser)
      .catch(err => { console.log(err)});
  }
  return (
    <>
      <Head>
        <title>Devtter 🐤</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppLayout>
        <Container>
          <Image src={logo} alt='logo' width={120} height={120} />
          <Title>Devtter</Title>
          <Subtitle>Talk about development with developers 👩‍💻👨‍💻</Subtitle>
          <div style={{ marginTop: 80 }}>
            <Button buttonType='secondary' onClick={handleClick}>
              <GitHub width={24} height={24} fill='#fff'/>
              Login with Github
            </Button>
          </div>
        </Container>
      </AppLayout>
    </>
  );
}
